name: ng2_g_signin
description: Google sign-in component for Angular2 Dart.
version: 0.3.2
author: ntaoo <ntaoo.g@gmail.com>
homepage: https://github.com/ntaoo/ng2_g_signin

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  angular: ^5.1.0
  js: ^0.6.0
